baseURL: "https://example.org/"

# multillingual configs
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    title: Frontend Mentor | Manage landing page
    languageName: English
    contentDir: content/en/
    menuFile: en.yaml
    params:
      description: description in English
    weight: 1
    rss: true
  de:
    title: Frontend Mentor | Landingpage verwalten
    languageName: Deutsch
    contentDir: content/de/
    menuFile: de.yaml
    weight: 2
    params:
      description: description in German
    rss: true

caches:
  images:
    dir: :cacheDir/images

# tailwind specific build commands
build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/notwatching/hugo_stats\.json
      target: css
    - source: (postcss|tailwind)\.config\.js
      target: css
module:
  mounts:
    - source: assets
      target: assets
    - disableWatch: true
      source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json
